name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y shellcheck bats
      - name: ShellCheck
        run: |
          if [ -f bin/arch-wsl ]; then
            shellcheck -x bin/arch-wsl lib/bash/*.sh
          else
            echo "bin/arch-wsl not found; shellchecking lib/bash only"
            shellcheck -x lib/bash/*.sh
          fi
      - name: Bats tests
        run: bats tests/bats || true
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
      - name: Analyze PowerShell
        shell: pwsh
        run: |
          if (Test-Path 'src/ps') {
            Invoke-ScriptAnalyzer -Path src/ps -Recurse -Severity Warning
          } else {
            Write-Host 'src/ps not found; skipping analysis'
          }
