name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y shellcheck bats
      - name: ShellCheck
        run: shellcheck -x bin/arch-wsl lib/bash/*.sh
      - name: Bats tests
        run: bats tests/bats || true
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
      - name: Analyze PowerShell
        shell: pwsh
        run: Invoke-ScriptAnalyzer -Path src/ps -Recurse -Severity Warning
